### ISSUE TITLE
Cannot import latest version of PayUUPI, PayUUPICore, PayULogger, PayUNetworking

### ISSUE THREAD

**Issue by guru-mtech** [payu-intrepos/payu-upi-ios-sdk#4]
![Screenshot 2020-06-25 at 5 14 33 PM](https://user-images.githubusercontent.com/64658840/85714024-a343b900-b707-11ea-9371-1f17538b41d8.png)

can any one help to solve this issue??

**Comment by mahi8813** [comment]
We are facing the same issue. Can u provide frameworks that works across all Xcode versions.  Right now, it seems that  we have to use same Xcode versions as that of Xcode used to build the frameworks. In our team, people use multiple Xcode versions.

**Comment by guru-mtech** [comment]
I am Using Xcode 11.2.1

**Comment by stanydsouza** [comment]
Even I am facing this issue. Please resolve this I have a urgent need of this framework

**Comment by RajvinderPayU** [comment]
@stanydsouza which version are you using? As the latest version (3.0.1) is ABI stable and works with swift 5.2 and above.

**Comment by rohitrvayuz** [comment]
Not working.

> Failed to build module 'PayUUPICoreKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.





### Xcode 13

**Comment by amitmishra0807** [comment]
> Not working.
> 
> > Failed to build module 'PayUUPICoreKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.
> 
> ### Xcode 13

First tell us the Mac OS name with m1 chip or intel based
if you are using M1 chip so please run project in real device

If any issue send mail on - mobile.integration@payu.in with details.

**Comment by rohitrvayuz** [comment]
I am using MacBook Pro M1

And I am running it on real device iPhone 7 and iPhone XS Max

**Comment by rohitrvayuz** [comment]
<img width="492" alt="Screenshot 2022-01-10 at 12 51 51" src="https://user-images.githubusercontent.com/78350161/148730568-e33f77b0-c98d-4311-9a87-a7b7a0714980.png">
<img width="498" alt="Screenshot 2022-01-10 at 12 51 56" src="https://user-images.githubusercontent.com/78350161/148730575-3ab8b36b-2e0d-4519-9ef2-82c4b4f9ddf4.png">
<img width="494" alt="Screenshot 2022-01-10 at 12 52 02" src="https://user-images.githubusercontent.com/78350161/148730577-a6500539-ac44-482f-9374-62d7b07cf61f.png">
<img width="698" alt="Screenshot 2022-01-10 at 12 55 25" src="https://user-images.githubusercontent.com/78350161/148730607-d059ec3c-3cef-4413-b112-94434607543d.png">
<img width="642" alt="Screenshot 2022-01-10 at 12 55 39" src="https://user-images.githubusercontent.com/78350161/148730612-65c75fea-db54-42ee-9f6c-8b81d7569fa2.png">

**Comment by ShubhGar** [comment]
Please change check minimum deployment target
