### ISSUE TITLE
UPI txn successful but response error

### ISSUE THREAD

**Issue by AmodD** [payu-intrepos/payu-upi-ios-sdk#8]
Having an issue with UPI payments only !

The UPI payment goes through as money is deducted at Bank but server side webhook callback does not happen and we get error response on client(mobile) 

403403PayUParamsKit.PayUError
Log : [Optional(“Failure Response:“), Optional({
  merchantResponse = “<null>“;
  payuResponse = “{\“status\“: \“failure\“,\“unmappedstatus\“: \“failed\“,\“error_Message\“:\“Error in decoding payment response\“}”;
})]

**Comment by RajvinderPayU** [comment]
Please get in touch with us on mobile.integration@payu.in with your merchant details.
